### ISSUE TITLE
Issues with vertical text (most specifically, prolonged sound marks)

### ISSUE THREAD

**Issue by citrusella** [FukeiSubs/SakuraGakuin-Disks#11]
I don't know if this is an issue with the file or if for some reason my player can't properly render it, but when Japanese is rendered vertically, the [dash that prolongs the sound before it](https://en.wikipedia.org/wiki/Ch%C5%8Donpu) (as in: su_u_pa_a_ redi_i_... this thing: ー ) should be rendered vertically, like a straight line downward, but it's not for the sub file I'm using. See below:

![mezase](https://cloud.githubusercontent.com/assets/14182450/11506114/b4bc21a0-981b-11e5-89d7-d16d09910531.png)

Thought I'd mention it here.

EDIT: I believe wavy dashes (the ones that look like tildes: ~) should be flipped as well but aren't. Could be wrong, since I've never had to use one in my limited vertical Japanese writing. XP

**Comment by EraYaN** [comment]
I am aware and I don't know how to fix it. It is using and "@ font" font so do you know what the replacement character is for that dash (ー)? (without replacing 一)

Someone with more experience in writing Japanese vertically can probably help, we basically need a vertical dash.

**Comment by citrusella** [comment]
:-/ I just combed over a few Japanese fonts in Microsoft Word just to see if there was a vertical dash present in their character sets, and the only way I could figure to flip it was to open Word in Japanese editing mode and set to vertical text... which still only rotates the character. I'll look around to see if there's any knowledge on this in the vast internet...

**Comment by EraYaN** [comment]
I found a solution: https://erayan.com/shared/2015-12-01_17-31-57.png looks okay right? (Punctuation is not rotated in @ fonts)

It is this character: (surrounded by spaces)

```
— (U+2013)
```

**Comment by citrusella** [comment]
I'd thought of the idea of using other characters but didn't know if it'd look right, but apparently it does!

That was a quick fix! 0_o

**Comment by EraYaN** [comment]
You do get weird breaking of lines though :( https://erayan.com/shared/2015-12-01_17-41-31.png https://erayan.com/shared/2015-12-01_17-42-03.png

I think due to the presence of spaces.

**Comment by citrusella** [comment]
...Ooh.

Perhaps I'll keep looking around, just in case there's a better option. (I actually thought I was onto something before I saw your solution, but the link I clicked was dead. XP)

**Comment by citrusella** [comment]
I don't know what this guy did, but his dashes are properly aligned, oddly: http://ssadev.blogspot.com/2011/07/vertical-writing.html

Looking at [this](https://code.google.com/p/libass/issues/detail?id=85), it looks like proper rendering of the dashes _might_ require a certain level of HarfBuzz support, but I have no idea if that's even the problem considering some problem characters in that issue aren't problems here (i.e. quotes are properly rotated). Could also potentially be a problem with the font.

_invokes Gone with the Wind reference_ ...I don't know nothing about subbing movies. XP

**Comment by EraYaN** [comment]
Sadly VSFilter (the ASS renderer) does not support OpenType. Basically the only thing now would be to use a non-space space character so no breaking occurs. ;)

**Comment by citrusella** [comment]
Ah, that's too bad. :-/

In related (as in, strange rotation) news, there appear to be two types of question mark in use:

? (used in Mezase! Super Lady, among other things) flips onto its side

![mezase2](https://cloud.githubusercontent.com/assets/14182450/11516149/a60bd9f0-984f-11e5-99ea-814a0c7eb334.png)

whereas ？(fullwidth, used in Sleep Wonder's bridge, at least) stays upright

![sleep wonder](https://cloud.githubusercontent.com/assets/14182450/11516178/c9e903de-984f-11e5-8ed9-141ad4471160.png)

Part of me wonders if the fullwidth ！flips similarly in relation to the Latin/halfwidth form. XP

Upright versus flipped for those seems slightly less important, but I thought I'd bring it up.

**Comment by EraYaN** [comment]
Fixed in 4ad1ea89
