### ISSUE TITLE
Intro to 'Mesaze! Super Lady -2015 nendo-'

### ISSUE THREAD

**Issue by EraYaN** [FukeiSubs/SakuraGakuin-Disks#23]

**Comment by The-Thrawn** [comment]
Partial translation by KaigaiFukei added. 6 lines still need translation.

**Comment by pootedesu** [comment]
There is a section where Mori-Sensei is almost completely unintelligible. Even slowing it down and having a native listener double check, we can only make out 75% of what he is saying. Might want to have someone triple check line 17.
