### ISSUE TITLE
MC 2 a few lines still need translation

### ISSUE THREAD

**Issue by EraYaN** [FukeiSubs/SakuraGakuin-Disks#32]

**Comment by The-Thrawn** [comment]
MC 2 has been timed and 99% translated by gakushabaka

**Comment by The-Thrawn** [comment]
Lines that are still untranslated in MC2.ass
47
49
50
78
113

**Comment by pootedesu** [comment]
Please verify fix and close.

**Comment by The-Thrawn** [comment]
Line 78 still needs translation.

**Comment by pootedesu** [comment]
Oops, must have missed that one. Will do it this evening after work.

**Comment by The-Thrawn** [comment]
Awesome :D
