### ISSUE TITLE
MC 4 a few lines still need translation.

### ISSUE THREAD

**Issue by EraYaN** [FukeiSubs/SakuraGakuin-Disks#36]

**Comment by The-Thrawn** [comment]
Lines that are still untranslated in MC4.ass

59
69
80

**Comment by pootedesu** [comment]
I translated these lines and have it checked into local Git, but when I try to push it is giving me a 403 forbidden. Do I need to be added?

**Comment by EraYaN** [comment]
I have invited you, accept the invite and you will be able to push your changes.

**Comment by pootedesu** [comment]
Please verify fix and close.
