### ISSUE TITLE
Song translations/revisions

### ISSUE THREAD

**Issue by DarrenTimothyChua** [FukeiSubs/SakuraGakuin-Disks#4]
There's three songs in the setlist we don't have translations for yet.
Gokigen Mr. Toropicarori
Piece de check
Planet Episode 008

And a couple songs that have very rough translations that need revising.
Mezase! Super Lady 2014
Spin in the Wind

Mezase! Super Lady 2014 translation can be found here: https://www.google.com/url?q=https%3A%2F%2Fwww.reddit.com%2Fr%2FSakuraGakuin%2Fcomments%2F2n2yrp%2Fcan_somebody_translate_into_english_this_song%2Fcmbffny&sa=D&sntz=1&usg=AFQjCNFra8KszhyQOu20O-_sfeTixQeC4Q
Spin in the Wind translation can be found here: https://www.reddit.com/r/SakuraGakuin/comments/2n2yrp/can_somebody_translate_into_english_this_song/cmbffny

EDIT: Some Mini-Pati songs haven't been translated either.
Happy Birthday
Princess ala mode
Acha Cha Kare

We can just translate the parts sung in the medley for now, we don't need the whole song.

**Comment by The-Thrawn** [comment]
School days also has a very rough translation tbh.

http://songforsmiling.forumid.net/t147-school-days

Lyrics for all of the songs @Shadeslayr mentioned and School Days 

[Gokigen Mr. Toropicarori](http://i.imgur.com/96HEKps.jpg)

[Piece de check](http://i.imgur.com/pRGVb9f.jpg)

[Mezase! Super Lady 2014](http://i.imgur.com/gKvw4ZV.jpg)

[Spin in the Wind](http://i.imgur.com/OoOmMDi.jpg)

[Planet Episode 008](http://i.imgur.com/zSaQKiT.jpg)

[School Days](http://i.imgur.com/ch4PbMA.jpg)

**Comment by DarrenTimothyChua** [comment]
@The-Thrawn I saw that on your spreadsheet. I thought it was good enough, but definitely if we can improve it, we should.

**Comment by DarrenTimothyChua** [comment]
Actually, I want to post links to some the available song translations to see if anyone can improve them.

School Days http://songforsmiling.forumid.net/t147-school-days
Hello Ivy https://drive.google.com/file/d/0B64L034DuSs2OGtuaFhPMW1kSUU/view
Takaramono https://www.reddit.com/r/SakuraGakuin/comments/38nbpb/%E5%AE%9D%E7%89%A9takaramono_english_lyric_translation/
Yume ni Mukatte https://drive.google.com/file/d/0B64L034DuSs2cEhzeF9UTHNsWlk/view

**Comment by fernaldi01** [comment]
@Shadeslayr Upgoon has just miraculously translated Planet Episode 008 eventhough no one requested to him:
https://drive.google.com/file/d/0B1nPIYT2qIFtcGE3YmhheFhuRXM/view?pli=1

In that spur of the moment, I requested the translations of these songs as well, and he said he'll be prioritizing on these songs:
- Gokigen Mr. Toropicarori
- Piece de check
- Happy Birthday
- Princess ala mode
- Acha Cha Kare

Is it okay with you, ShadeSlayr? Are there any song that you asked the translation from someone else so I could cross some songs out of that list thus minimizing Upgoon's priority?

**Comment by DarrenTimothyChua** [comment]
@fernaldi01  Thank you for posting this! Please tell Upgoon to hold off on translating Piece de Check because redfreesias03 has it on her song translation list. http://redfreesias03.tumblr.com/requests

Also, please tell him that he doesn't need to translate the whole of the 3 MiniPati songs yet, just the parts that were sung in the medley. Although if he wants to, that would be even more awesome :)

And I don't want to ask too much of him, but if it's possible, please ask him to check/revise the translations for the following songs:

Mezase! Super Lady 2014 https://www.reddit.com/r/SakuraGakuin/comments/2n2yrp/can_somebody_translate_into_english_this_song/cmbffny
Spin in the Wind https://www.reddit.com/r/SakuraGakuin/comments/2n2yrp/can_somebody_translate_into_english_this_song/cmbffny
School days http://songforsmiling.forumid.net/t147-school-days
Hello! IVY https://drive.google.com/file/d/0B64L034DuSs2OGtuaFhPMW1kSUU/view

**Comment by ghost** [comment]
heyo! 
http://redfreesias03.tumblr.com/post/124253528096/happy-birthday

**Comment by fernaldi01** [comment]
@Shadeslayr Translation of Gokigen! Mr. Tropicalory by Upgoon:
https://drive.google.com/file/d/0B1nPIYT2qIFtb002WTlWYUFGeUk/view?pli=1

So that makes....

Untranslated songs:
- Piece de Check
- Princess ala Mode
- Acha! Cha! Kare

Translations that need revisions:
- Mezase! Super Lady 2014
- Spin in the Wind
- School days (currently ongoing, by Upgoon)
- Hello! IVY

**Comment by DarrenTimothyChua** [comment]
@soupman2001 Thank you!

@fernaldi01 Man, Upgoon is really cool for doing this! Thank you to him and to you. Can you please ask him to include romaji for Mezase and Spin in the Wind?

**Comment by ghost** [comment]
These lyrics and choreography have almost made Gokigen! Mr. Tropicalorie my favorite track on the 2014 Nendo album.

**Comment by DarrenTimothyChua** [comment]
Yeah, I really liked the 2014 RTG performance of it.

**Comment by The-Thrawn** [comment]
gakushabaka did a partial translation of Acha! Cha! Kare a while back, I don't think he finished it though.

http://pastebin.com/LGQyhhEF

**Comment by DarrenTimothyChua** [comment]
@The-Thrawn Thanks. There's just one line there that I need translated.  

Mune ippai no kono koushinryou mo (haa...)

If someone could help translate that, it would be awesome.

**Comment by The-Thrawn** [comment]
@Shadeslayr  http://redfreesias03.tumblr.com/post/124550744961/sayonara-namida-goodbye-tears

http://redfreesias03.tumblr.com/post/124550473086/piece-de-check-check-out-this-piece

http://redfreesias03.tumblr.com/post/124550505691/chime-school-bell

**Comment by DarrenTimothyChua** [comment]
@The-Thrawn Unfortunately Sayonara Namida is useless for me here since they didn't perform it in RTG2014 Final XD Chime, too.

**Comment by fernaldi01** [comment]
A proper translation of School days by Upgoon:

https://drive.google.com/file/d/0B1nPIYT2qIFtc19jaDBWem1tb3c/view?pli=1

So that makes...

Untranslated songs:
- Acha! Cha! Kare (Only need "Mune ippai no kono koushinryou mo" line)

Translations that need revisions:
- Mezase! Super Lady 2014
- Spin in the Wind
- Hello! IVY

**Comment by DarrenTimothyChua** [comment]
@fernaldi01 thanks! Thank you to Upgoon as well!

**Comment by fernaldi01** [comment]
Maybe these Upgoon's translations have been posted already, but anyway, just for archiving purpose >_<
- Princess a la Mode: https://drive.google.com/file/d/0B1nPIYT2qIFtcFFxbW80SnUzalk/view?pli=1
- School days: https://drive.google.com/file/d/0B1nPIYT2qIFtc19jaDBWem1tb3c/view?pli=1

**Comment by DarrenTimothyChua** [comment]
@fernaldi01 Yep, I've finished subbing those two songs. Now I'm just patiently waiting for Mezase! 2014 and Spin in the Wind :D

**Comment by EraYaN** [comment]
All songs are translated, for errors make a new issue.
