### ISSUE TITLE
Talk during Suimin Busoku needs translation.

### ISSUE THREAD

**Issue by The-Thrawn** [FukeiSubs/SakuraGakuin-Disks#47]
Relevant sections are timed in the suimin-busoku-talk.ass file.

**Comment by EraYaN** [comment]
Could you split the the talks from the lyrics? This way we can have people pick and choose again.

**Comment by The-Thrawn** [comment]
Sure, shouldn't take long.

**Comment by The-Thrawn** [comment]
This has now been translated by gakushabaka and added.
