### ISSUE TITLE
Overall observations

### ISSUE THREAD

**Issue by The-Thrawn** [FukeiSubs/SakuraGakuin-Disks#5]
I quickly merged all the sub files we have so far (for personal use, just so I can see how much is left to do), and just wanted to raise a few issues.

Mezase super lady has no Eng or JPN subs yet.

gokigen-mr-toropikarori-lyrics-jpn had no timing at all. (Fixed now)

At the start of school days Moa says something to the audience that doesn't seem to be covered in any of the sub files. (Time stamp 0:04:49.45)

At the start of Aogeba Taoutoshi Ooga Saki says something to the audience that doesn't seem to be covered in any of the sub files. (Time stamp 0:18:53.37)

**Comment by EraYaN** [comment]
Are those last two things in the timed files? Or are they completely absent?

The first should be in school-days.ass (new file)
The second should be in aogeba-toutoshi.ass (new file)

I will create those files. If someone is willing to pickup translation for those two parts. That would be cool.

**Comment by The-Thrawn** [comment]
Completely absent, it's just two short comments to the audience, but I thought it was worth mentioning.

I'm still watching through the subs now, I'm up to Piece de check so far.

**Comment by EraYaN** [comment]
Fixed second part in fd3b064d6c84bd8036205bc2a08d3adc2642fd38
